"""
Red Dragon MUD - Complete Guild Tree System
All guilds, sub-guilds, skills, and spells from Islands of Myth
"""

from evennia import Command, CmdSet

# Guild levels
GUILD_LEVELS = {
    "alpha": 1,
    "beta": 2,
    "gamma": 3,
    "delta": 4,
    "epsilon": 5,
    "zeta": 6,
    "eta": 7,
    "theta": 8,
    "iota": 9,
    "kappa": 10,
    "lambda": 11,
    "mu": 12,
    "nu": 13,
    "xi": 14,
    "omicron": 15,
    "pi": 16,
    "rho": 17,
    "sigma": 18,
    "tau": 19,
    "upsilon": 20,
    "phi": 21,
    "chi": 22,
    "psi": 23,
    "omega": 24,
    "bravo": 25,  # Special - used for warrior advanced
}

# Skill types
SKILL_TYPES = {
    "combat": "Combat skill",
    "attack": "Active attack",
    "protection": "Defensive buff",
    "mastery": "Passive mastery",
    "healing": "Healing skill",
    "miscellaneous": "Utility skill",
    "enchantment": "Item buff",
    "area": "Area attack",
    "party_protection": "Party buff",
}

# Complete guild database
GUILDS = {
    # WARRIOR TREE
    "warrior": {
        "name": "Warrior",
        "level": "alpha",
        "type": "fighter",
        "description": "Warriors are fighters who have chosen the path of mastering combat with the use of weapons.",
        "prerequisites": [],
        "equipment": "warrior_belt",
        "skills": {
            1: [("attack", "Combat", 459), ("tanking", "Mastery", 557)],
            2: [("weapon_skill_blunt", "Combat", 504)],
            3: [("flesh_of_stone", "Protection", 708)],
            4: [("honor_of_the_gods", "Mastery", 557)],
            5: [("weapon_skill_piercing", "Combat", 504)],
            6: [("punch", "Attack", 426)],
            8: [("weapon_skill_slashing", "Combat", 504)],
            10: [("essence_eye", "Mastery", 557), ("weapon_skill_whipping", "Combat", 504)],
            11: [("forearm_bash", "Attack", 739)],
            14: [("doublehit", "Combat", 940)],
            15: [("kick", "Attack", 940)],
            17: [("dodge", "Combat", 1316)],
            19: [("stun", "Combat", 940)],
            20: [("unarmed_combat", "Mastery", 1370)],
        },
        "parent": None,
        "children": ["knight", "defender_of_the_crown", "berserker", "traveler"],
    },

    "knight": {
        "name": "Knight",
        "level": "gamma",
        "type": "fighter",
        "description": "Knight guild members are taught how to fight offensively better.",
        "prerequisites": ["warrior"],
        "skills": {
            2: [("biofeedback", "Healing", 739)],
            4: [("strike", "Attack", 960)],
            5: [("multiweapons", "Combat", 940)],
            6: [("whirlwind_attack", "Combat", 940)],
            8: [("counter_dodge", "Combat", 940)],
            9: [("enhance_striking", "Mastery", 1084)],
            10: [("weaponmaster", "Combat", 1176)],
        },
        "parent": "warrior",
        "children": ["blade_dancer", "barbarian"],
    },

    "defender_of_the_crown": {
        "name": "Defender Of The Crown",
        "level": "gamma",
        "type": "fighter",
        "description": "Defenders are taught the basics in combat defense and protection with a shield.",
        "prerequisites": ["warrior"],
        "skills": {
            1: [("weapon_skill_shield", "Combat", 940)],
            3: [("unbalancing_blow", "Attack", 974)],
            4: [("shield_parry", "Combat", 1316)],
            5: [("motion_control", "Mastery", 1428)],
            6: [("riposte", "Combat", 1176)],
            7: [("willpower", "Combat", 1598)],
            10: [("shield_deflection", "Combat", 1457), ("defensive_stance", "Protection", 739)],
        },
        "parent": "warrior",
        "children": ["shield_master"],
    },

    "berserker": {
        "name": "Berserker",
        "level": "gamma",
        "type": "fighter",
        "description": "Berserkers are taught better control over their own body to enhance fighting.",
        "prerequisites": ["warrior"],
        "skills": {
            1: [("resist_pain", "Protection", 739)],
            2: [("biofeedback", "Healing", 739)],
            4: [("strike", "Attack", 960), ("body_control", "Mastery", 1312)],
            6: [("fevered_strength", "Protection", 772)],
            7: [("ignore_pain", "Protection", 940)],
            9: [("enhance_striking", "Mastery", 1084)],
            10: [("berserker_rage", "Combat", 1034), ("berserker_stance", "Protection", 739)],
        },
        "parent": "warrior",
        "children": ["barbarian", "flogger", "thruster"],
    },

    "traveler": {
        "name": "Traveler",
        "level": "gamma",
        "type": "miscellaneous",
        "description": "Travelers are taught the basics at surviving in the wilderness.",
        "prerequisites": ["warrior", "martial_artist", "abjurer", "elemental", "evoker", "necromancer"],
        "skills": {
            1: [("tinning", "Miscellaneous", 705)],
            2: [("scavenge_wood", "Miscellaneous", 571), ("torch_making", "Miscellaneous", 571)],
            3: [("fire_building", "Miscellaneous", 604)],
            4: [("skinning", "Miscellaneous", 638)],
            5: [("hunting", "Miscellaneous", 705), ("fishing", "Mastery", 1541)],
            6: [("camping", "Protection", 705)],
            8: [("herb_gathering", "Miscellaneous", 873)],
            9: [("herb_preservation", "Mastery", 501)],
            10: [("awareness", "Mastery", 1633)],
        },
        "parent": "warrior",
        "children": ["thruster"],
    },

    "blade_dancer": {
        "name": "Blade Dancer",
        "level": "bravo",
        "type": "fighter",
        "description": "Blade Dancers master the use of slashing type weapons with grace and finesse.",
        "prerequisites": ["berserker", "defender_of_the_crown", "knight"],
        "skills": {
            1: [("bladed_fury", "Attack", 1561)],
            3: [("devastating_attack", "Combat", 1748)],
            4: [("endowment_of_the_gods", "Mastery", 1633)],
            5: [("advanced_whirlwind_attack", "Combat", 1479)],
            6: [("blade_dance", "Protection", 1057), ("master_of_the_dance", "Mastery", 1715)],
            7: [("singing_blade", "Enchantment", 1657), ("arc_of_elegance", "Area", 1249)],
            8: [("slashing_weapons_mastery", "Combat", 1345), ("cry_of_the_berserker", "Party_protection", 1201)],
        },
        "parent": "knight",
        "children": [],
    },

    "barbarian": {
        "name": "Barbarian",
        "level": "bravo",
        "type": "fighter",
        "description": "Barbarians master the use of blunt type weapons with strength and ferociousness.",
        "prerequisites": ["knight", "defender_of_the_crown", "berserker"],
        "skills": {
            2: [("deathblow", "Attack", 1498)],
            3: [("endowment_of_the_gods", "Mastery", 1633)],
            4: [("devastating_attack", "Combat", 1748)],
            5: [("advanced_whirlwind_attack", "Combat", 1479)],
            6: [("stunning_blow", "Combat", 2084), ("bloodlust", "Mastery", 1960)],
            7: [("whirlwind_strike", "Area", 1249)],
            8: [("blunt_weapons_mastery", "Combat", 1345), ("cry_of_the_berserker", "Party_protection", 1201)],
        },
        "parent": "knight",
        "children": [],
    },

    "shield_master": {
        "name": "Shield Master",
        "level": "bravo",
        "type": "fighter",
        "description": "Shield Masters specialize in wielding shield type weapons.",
        "prerequisites": ["knight", "berserker", "defender_of_the_crown"],
        "skills": {
            1: [("willpower", "Combat", 1598)],
            2: [("fighting_instinct", "Mastery", 1878)],
            3: [("endowment_of_the_gods", "Mastery", 1633)],
            5: [("weapon_parry", "Combat", 1412)],
            6: [("advanced_parry", "Combat", 1748), ("enhanced_deflection", "Combat", 1815)],
            7: [("double_bash", "Combat", 1547)],
            8: [("shield_fighting", "Combat", 1345), ("defenders_warcry", "Party_protection", 1201)],
        },
        "parent": "defender_of_the_crown",
        "children": [],
    },

    "flogger": {
        "name": "Flogger",
        "level": "bravo",
        "type": "fighter",
        "description": "Floggers master the use of whipping type weapons.",
        "prerequisites": ["defender_of_the_crown", "knight", "berserker"],
        "skills": {
            1: [("lacerate", "Attack", 1441)],
            2: [("immobilize", "Attack", 1153)],
            3: [("devastating_attack", "Combat", 1748)],
            4: [("endowment_of_the_gods", "Mastery", 1633)],
            5: [("whipping_weapons_mastery", "Combat", 1950)],
            6: [("advanced_whirlwind_attack", "Combat", 1479)],
            7: [("lash_of_dominion", "Area", 1249)],
            8: [("lightning_whip", "Enchantment", 1345), ("cry_of_the_berserker", "Party_protection", 1201)],
            10: [("entangle", "Attack", 1297)],
        },
        "parent": "berserker",
        "children": [],
    },

    "thruster": {
        "name": "Thruster",
        "level": "bravo",
        "type": "fighter",
        "description": "Thrusters master the use of piercing type weapons.",
        "prerequisites": ["defender_of_the_crown", "berserker", "knight"],
        "skills": {
            2: [("impale", "Attack", 1441)],
            3: [("devastating_attack", "Combat", 1748)],
            4: [("endowment_of_the_gods", "Mastery", 1633)],
            5: [("sharpen_weapon", "Enchantment", 1345)],
            6: [("advanced_whirlwind_attack", "Combat", 1479)],
            7: [("piercing_weapons_mastery", "Combat", 1345), ("spearwind_thrust", "Area", 1249)],
            8: [("spot_weak_point", "Mastery", 1878), ("cry_of_the_berserker", "Party_protection", 1201)],
            10: [("wrist_flick", "Mastery", 2286)],
        },
        "parent": "berserker",
        "children": [],
    },

    "champion_of_the_crown": {
        "name": "Champion Of The Crown",
        "level": "omicron",
        "type": "fighter",
        "description": "Champions are taught all the secrets in turning a warrior into a true champion in combat.",
        "prerequisites": ["defender_of_the_crown", "berserker", "knight"],
        "skills": {
            2: [("crippling_blow", "Combat", 2405)],
            3: [("strike_weakness", "Combat", 2213)],
            4: [("weapon_maneuvers", "Mastery", 3740)],
            5: [("stun_resistance", "Combat", 2501)],
            6: [("charge", "Attack", 3656), ("champion_lore", "Mastery", 2570)],
            8: [("champion_trance", "Protection", 2640)],
        },
        "parent": "knight",
        "children": [],
    },
}

# Skill detail database
SKILL_DATABASE = {
    "attack": {
        "name": "Attack",
        "type": "Combat",
        "cost": 459,
        "description": "Determines hit chance and damage.",
        "creator": "Unknown",
    },
    "tanking": {
        "name": "Tanking",
        "type": "Mastery",
        "cost": 557,
        "description": "Protect party members. Warrior is unrivaled in tanking abilities.",
        "creator": "Daneel",
    },
    "weapon_skill_blunt": {
        "name": "Weapon Skill Blunt",
        "type": "Combat",
        "cost": 504,
        "description": "Handle blunt weapons.",
        "creator": "Unknown",
    },
    "flesh_of_stone": {
        "name": "Flesh of Stone",
        "type": "Protection",
        "cost": 708,
        "description": "Focus inner strength to turn body into stone, blocking physical damage. More effective for less experienced.",
        "ep_cost": 162,
        "using_time": "2 rounds",
        "creator": "Pavilion",
    },
    "honor_of_the_gods": {
        "name": "Honor of the Gods",
        "type": "Mastery",
        "cost": 557,
        "description": "Spiritual connection grants more health during regeneration.",
        "creator": "Pavilion",
    },
    "weapon_skill_piercing": {
        "name": "Weapon Skill Piercing",
        "type": "Combat",
        "cost": 504,
        "description": "Master piercing weapons.",
        "creator": "Unknown",
    },
    "punch": {
        "name": "Punch",
        "type": "Attack",
        "cost": 426,
        "description": "Unarmed strike.",
        "damage": "Extremely low",
        "damage_type": "Physical",
        "ep_cost": 52,
        "using_time": "2 rounds",
        "affecting_stats": ["str", "dex"],
        "creator": "Pavilion",
    },
    "weapon_skill_slashing": {
        "name": "Weapon Skill Slashing",
        "type": "Combat",
        "cost": 504,
        "description": "Master slashing weapons.",
        "creator": "Unknown",
    },
    "weapon_skill_whipping": {
        "name": "Weapon Skill Whipping",
        "type": "Combat",
        "cost": 504,
        "description": "Master whip weapons.",
        "creator": "Unknown",
    },
    "essence_eye": {
        "name": "Essence Eye",
        "type": "Mastery",
        "cost": 557,
        "description": "Awareness of spell casting and skill timing. Toggle with toggle_essence.",
        "creator": "Onyx",
    },
    "forearm_bash": {
        "name": "Forearm Bash",
        "type": "Attack",
        "cost": 739,
        "description": "Weak point strike with forearm.",
        "damage": "Low",
        "damage_type": "Physical",
        "ep_cost": 100,
        "using_time": "2 rounds",
        "affecting_stats": ["str", "dex"],
        "creator": "Unknown",
    },
    "doublehit": {
        "name": "Doublehit",
        "type": "Combat",
        "cost": 940,
        "description": "Score extra hit in combat.",
        "creator": "Unknown",
    },
    "kick": {
        "name": "Kick",
        "type": "Attack",
        "cost": 940,
        "description": "Leg strike.",
        "damage": "Low",
        "damage_type": "Physical",
        "ep_cost": 116,
        "using_time": "2 rounds",
        "affecting_stats": ["str", "dex"],
        "creator": "Sigwald",
    },
    "dodge": {
        "name": "Dodge",
        "type": "Combat",
        "cost": 1316,
        "description": "Quick and nimble, dodge combat blows. Affected by capacity (how much you carry).",
        "creator": "Unknown",
    },
    "stun": {
        "name": "Stun",
        "type": "Combat",
        "cost": 940,
        "description": "Knock victim senseless for a few rounds.",
        "creator": "Unknown",
    },
    "unarmed_combat": {
        "name": "Unarmed Combat",
        "type": "Mastery",
        "cost": 1370,
        "description": "Use limbs in battle. Enhances punches, kicks, headbutts.",
        "creator": "Sigwald",
    },
    "biofeedback": {
        "name": "Biofeedback",
        "type": "Healing",
        "cost": 739,
        "description": "Focus strength inwards, healing wounds.",
        "healing": "Under average",
        "ep_cost": 240,
        "using_time": "4 rounds",
        "creator": "Unknown",
    },
    "strike": {
        "name": "Strike",
        "type": "Attack",
        "cost": 960,
        "description": "Crushing assault with energy focus.",
        "damage": "Noticeable",
        "damage_type": "Physical",
        "ep_cost": 192,
        "using_time": "3 rounds",
        "affecting_stats": ["str", "dex"],
        "creator": "Unknown",
    },
    "multiweapons": {
        "name": "Multiweapons",
        "type": "Combat",
        "cost": 940,
        "description": "Use multiple weapons during combat.",
        "creator": "Unknown",
    },
    "whirlwind_attack": {
        "name": "Whirlwind Attack",
        "type": "Combat",
        "cost": 940,
        "description": "Score extra hit in combat. Double hit needed.",
        "creator": "Unknown",
    },
    "counter_dodge": {
        "name": "Counter Dodge",
        "type": "Combat",
        "cost": 940,
        "description": "Counter target's attempt at dodging.",
        "creator": "Unknown",
    },
    "enhance_striking": {
        "name": "Enhance Striking",
        "type": "Mastery",
        "cost": 1084,
        "description": "Enhances strike skill damage.",
        "creator": "Swashbuckler",
    },
    "weaponmaster": {
        "name": "Weaponmaster",
        "type": "Combat",
        "cost": 1176,
        "description": "Most important armed combat skill. Increases base hits and critical hits.",
        "creator": "Sigwald",
    },
    "weapon_skill_shield": {
        "name": "Weapon Skill Shield",
        "type": "Combat",
        "cost": 940,
        "description": "Master shields for extra shield bashing attack.",
        "creator": "Sigwald",
    },
    "unbalancing_blow": {
        "name": "Unbalancing Blow",
        "type": "Attack",
        "cost": 974,
        "description": "Violent bashing blow to unsettle opponent.",
        "damage": "Under average",
        "damage_type": "Physical",
        "ep_cost": 202,
        "using_time": "3 rounds",
        "affecting_stats": ["str"],
        "creator": "Sigwald, Samael",
    },
    "shield_parry": {
        "name": "Shield Parry",
        "type": "Combat",
        "cost": 1316,
        "description": "Block blows with shield.",
        "creator": "Sigwald",
    },
    "motion_control": {
        "name": "Motion Control",
        "type": "Mastery",
        "cost": 1428,
        "description": "Control movements to optimize actions. Less effective in combat.",
        "creator": "Sigwald",
    },
    "riposte": {
        "name": "Riposte",
        "type": "Combat",
        "cost": 1176,
        "description": "Turn successful parry into offensive maneuver.",
        "creator": "Pavilion",
    },
    "willpower": {
        "name": "Willpower",
        "type": "Combat",
        "cost": 1598,
        "description": "Focus will to ignore aftermath of stunning blows.",
        "creator": "Sigwald",
    },
    "shield_deflection": {
        "name": "Shield Deflection",
        "type": "Combat",
        "cost": 1457,
        "description": "Partially deflect distant attacks including magical.",
        "creator": "Sigwald, Samael",
    },
    "defensive_stance": {
        "name": "Defensive Stance",
        "type": "Protection",
        "cost": 739,
        "description": "Form defensive stance lowering outgoing and incoming damage.",
        "duration": "Extremely high",
        "ep_cost": 402,
        "using_time": "4 rounds",
        "creator": "Snoop",
    },
    "resist_pain": {
        "name": "Resist Pain",
        "type": "Protection",
        "cost": 739,
        "description": "Mind resists pain, taking less damage.",
        "duration": "Average",
        "ep_cost": 402,
        "using_time": "4 rounds",
        "affecting_stats": ["con"],
        "creator": "Swashbuckler",
    },
    "body_control": {
        "name": "Body Control",
        "type": "Mastery",
        "cost": 1312,
        "description": "Control over body, enhancing fighting abilities.",
        "creator": "Sigwald",
    },
    "fevered_strength": {
        "name": "Fevered Strength",
        "type": "Protection",
        "cost": 772,
        "description": "Enhance physical strength and dexterity.",
        "duration": "Average",
        "ep_cost": 386,
        "using_time": "3 rounds",
        "affecting_stats": ["sta"],
        "creator": "swashbuckler",
    },
    "ignore_pain": {
        "name": "Ignore Pain",
        "type": "Protection",
        "cost": 940,
        "description": "Completely ignore pain, ignoring most physical damage.",
        "duration": "Low",
        "ep_cost": 402,
        "using_time": "5 rounds",
        "affecting_stats": ["con"],
        "creator": "swashbuckler",
    },
    "berserker_rage": {
        "name": "Berserker Rage",
        "type": "Combat",
        "cost": 1034,
        "description": "Furiously strike foes doing more hits.",
        "creator": "Swashbuckler",
    },
    "berserker_stance": {
        "name": "Berserker Stance",
        "type": "Protection",
        "cost": 739,
        "description": "Increase critical hit chance but lower defense and take more damage.",
        "duration": "Extremely high",
        "ep_cost": 402,
        "using_time": "4 rounds",
        "creator": "Snoop",
    },
    "tinning": {
        "name": "Tinning",
        "type": "Miscellaneous",
        "cost": 705,
        "description": "Salvage meat from corpse in non-perishable form. Requires tinning kit.",
        "ep_cost": 20,
        "using_time": "1 round",
        "creator": "Onyx",
    },
    "scavenge_wood": {
        "name": "Scavenge Wood",
        "type": "Miscellaneous",
        "cost": 571,
        "description": "Find wood for campfire without harming nature.",
        "ep_cost": 246,
        "using_time": "6 rounds",
        "creator": "Samael",
    },
    "torch_making": {
        "name": "Torch Making",
        "type": "Miscellaneous",
        "cost": 571,
        "description": "Make fortune torch from available materials.",
        "ep_cost": 262,
        "using_time": "4 rounds",
        "creator": "Unknown",
    },
    "fire_building": {
        "name": "Fire Building",
        "type": "Miscellaneous",
        "cost": 604,
        "description": "Create campfire for warmth. Strength depends on skill.",
        "ep_cost": 350,
        "using_time": "4 rounds",
        "creator": "Unknown",
    },
    "skinning": {
        "name": "Skinning",
        "type": "Miscellaneous",
        "cost": 638,
        "description": "Skin animal corpse to make pelt. Needs edged weapon.",
        "ep_cost": 234,
        "using_time": "5 rounds",
        "creator": "Sigwald",
    },
    "hunting": {
        "name": "Hunting",
        "type": "Miscellaneous",
        "cost": 705,
        "description": "Catch small game for food.",
        "ep_cost": 276,
        "using_time": "10 rounds",
        "creator": "Sigwald",
    },
    "fishing": {
        "name": "Fishing",
        "type": "Mastery",
        "cost": 1541,
        "description": "Enhance ability to hook, cast, and reel in while fishing.",
        "creator": "Prophet",
    },
    "camping": {
        "name": "Camping",
        "type": "Protection",
        "cost": 705,
        "description": "Make camp and get rest. Speeds healing and regeneration. Requires sleeping bag.",
        "duration": "Low",
        "ep_cost": 262,
        "using_time": "5 rounds",
        "creator": "Sigwald",
    },
    "herb_gathering": {
        "name": "Herb Gathering",
        "type": "Miscellaneous",
        "cost": 873,
        "description": "Search for rare herbs for healing. Herbalists more efficient.",
        "ep_cost": 262,
        "using_time": "15 rounds",
        "creator": "Sigwald",
    },
    "herb_preservation": {
        "name": "Herb Preservation",
        "type": "Mastery",
        "cost": 501,
        "description": "Keep herbs efficient over extended durations.",
        "creator": "Sigwald",
    },
    "awareness": {
        "name": "Awareness",
        "type": "Mastery",
        "cost": 1633,
        "description": "More aware of environment. Likely to catch rogues in criminal acts.",
        "creator": "Pavilion",
    },
    "bladed_fury": {
        "name": "Bladed Fury",
        "type": "Attack",
        "cost": 1561,
        "description": "Lightning fast blade patterns creating dazzling attack.",
        "damage": "Average",
        "damage_type": "Physical",
        "ep_cost": 178,
        "using_time": "3 rounds",
        "affecting_stats": ["dex"],
        "creator": "Unknown",
    },
    "devastating_attack": {
        "name": "Devastating Attack",
        "type": "Combat",
        "cost": 1748,
        "description": "Deliver painful attacks on critical hit opportunities.",
        "creator": "Sigwald",
    },
    "endowment_of_the_gods": {
        "name": "Endowment of the Gods",
        "type": "Mastery",
        "cost": 1633,
        "description": "Gods grant more endurance as he heals.",
        "creator": "Pavilion",
    },
    "advanced_whirlwind_attack": {
        "name": "Advanced Whirlwind Attack",
        "type": "Combat",
        "cost": 1479,
        "description": "Spin twice instead of once, giving extra hit.",
        "creator": "Unknown",
    },
    "blade_dance": {
        "name": "Blade Dance",
        "type": "Protection",
        "cost": 1057,
        "description": "Enhance dexterity for complex blows. Cannot be stacked.",
        "duration": "Above average",
        "ep_cost": 514,
        "using_time": "4 rounds",
        "affecting_stats": ["dex"],
        "creator": "Pavilion and Gwynn",
    },
    "master_of_the_dance": {
        "name": "Master of the Dance",
        "type": "Mastery",
        "cost": 1715,
        "description": "Increases duration and bonuses of blade dancer skills.",
        "creator": "Pavilion",
    },
    "singing_blade": {
        "name": "Singing Blade",
        "type": "Enchantment",
        "cost": 1657,
        "description": "Blade vibrates with music, gaining weapon class.",
        "duration": "Extremely high",
        "ep_cost": 630,
        "using_time": "5 rounds",
        "creator": "Pavilion",
    },
    "arc_of_elegance": {
        "name": "Arc of Elegance",
        "type": "Area",
        "cost": 1249,
        "description": "Swift and mighty sword slashes striking all nearby foes.",
        "damage": "High",
        "damage_type": "Physical",
        "ep_cost": 362,
        "using_time": "4 rounds",
        "affecting_stats": ["dex"],
        "creator": "Cash",
    },
    "slashing_weapons_mastery": {
        "name": "Slashing Weapons Mastery",
        "type": "Combat",
        "cost": 1345,
        "description": "Expertise with slashing weapons for better efficiency.",
        "creator": "Sigwald",
    },
    "cry_of_the_berserker": {
        "name": "Cry of the Berserker",
        "type": "Party_protection",
        "cost": 1201,
        "description": "Cry of rage enrages companions, increasing critical hit chance.",
        "duration": "Above average",
        "ep_cost": 686,
        "using_time": "2 rounds",
        "affecting_stats": ["con"],
        "creator": "Snoop",
    },
    "deathblow": {
        "name": "Deathblow",
        "type": "Attack",
        "cost": 1498,
        "description": "Ultimate bludgeoning. Chance to damage vital organs causing instant death.",
        "damage": "Important",
        "damage_type": "Physical",
        "ep_cost": 320,
        "using_time": "4 rounds",
        "affecting_stats": ["str"],
        "creator": "Sven",
    },
    "stunning_blow": {
        "name": "Stunning Blow",
        "type": "Combat",
        "cost": 2084,
        "description": "Heavy blows that stun opponent by sheer strength and precision.",
        "creator": "Sigwald",
    },
    "bloodlust": {
        "name": "Bloodlust",
        "type": "Mastery",
        "cost": 1960,
        "description": "Focus hatred and rage for powerful blows.",
        "creator": "Sven",
    },
    "whirlwind_strike": {
        "name": "Whirlwind Strike",
        "type": "Area",
        "cost": 1249,
        "description": "Whirlwind fury striking all opponents. Requires blunt weapon.",
        "damage": "High",
        "damage_type": "Physical",
        "ep_cost": 362,
        "using_time": "4 rounds",
        "affecting_stats": ["str", "dex"],
        "creator": "Sigwald",
    },
    "blunt_weapons_mastery": {
        "name": "Blunt Weapons Mastery",
        "type": "Combat",
        "cost": 1345,
        "description": "Incredible moves and hits with blunt weapons.",
        "creator": "Sigwald",
    },
    "fighting_instinct": {
        "name": "Fighting Instinct",
        "type": "Mastery",
        "cost": 1878,
        "description": "Enhanced intuition and instinct in battle. Increases dodge chance, reduces enemy critical strikes.",
        "creator": "Sigwald",
    },
    "weapon_parry": {
        "name": "Weapon Parry",
        "type": "Combat",
        "cost": 1412,
        "description": "Parry blow with offensive weapon.",
        "creator": "Sigwald",
    },
    "advanced_parry": {
        "name": "Advanced Parry",
        "type": "Combat",
        "cost": 1748,
        "description": "Elaborate shield techniques for master level parrying.",
        "creator": "Sigwald",
    },
    "enhanced_deflection": {
        "name": "Enhanced Deflection",
        "type": "Combat",
        "cost": 1815,
        "description": "Greatly enhance efficiency of deflections.",
        "creator": "Sigwald",
    },
    "double_bash": {
        "name": "Double Bash",
        "type": "Combat",
        "cost": 1547,
        "description": "Hit opponent twice in same attack with shield.",
        "creator": "Sigwald",
    },
    "shield_fighting": {
        "name": "Shield Fighting",
        "type": "Combat",
        "cost": 1345,
        "description": "Most efficient use of shield, enhancing shield damage.",
        "creator": "Sigwald",
    },
    "defenders_warcry": {
        "name": "Defenders Warcry",
        "type": "Party_protection",
        "cost": 1201,
        "description": "Prepare companions for battle, increasing health.",
        "duration": "Above average",
        "ep_cost": 686,
        "using_time": "2 rounds",
        "affecting_stats": ["con"],
        "creator": "Snoop",
    },
    "lacerate": {
        "name": "Lacerate",
        "type": "Attack",
        "cost": 1441,
        "description": "Powerful and deadly blows lashing opponent with force.",
        "damage": "Above average",
        "damage_type": "Physical",
        "ep_cost": 246,
        "using_time": "3 rounds",
        "affecting_stats": ["str", "dex"],
        "creator": "Sigwald",
    },
    "immobilize": {
        "name": "Immobilize",
        "type": "Attack",
        "cost": 1153,
        "description": "Wrap whip around opponent's legs, immobilizing them.",
        "damage": "Almost nothing",
        "damage_type": "Physical",
        "ep_cost": 264,
        "using_time": "1 round",
        "affecting_stats": ["str"],
        "creator": "Sigwald",
    },
    "whipping_weapons_mastery": {
        "name": "Whipping Weapons Mastery",
        "type": "Combat",
        "cost": 1950,
        "description": "Advanced ways to fight using whipping weapons.",
        "creator": "Sigwald",
    },
    "lash_of_dominion": {
        "name": "Lash of Dominion",
        "type": "Area",
        "cost": 1249,
        "description": "Masterfully wield whip unleashing powerful lashes against all enemies.",
        "damage": "High",
        "damage_type": "Physical",
        "ep_cost": 362,
        "using_time": "4 rounds",
        "affecting_stats": ["str", "dex"],
        "creator": "Cash",
    },
    "lightning_whip": {
        "name": "Lightning Whip",
        "type": "Enchantment",
        "cost": 1345,
        "description": "Increase whip speed and power. Enhances lacerate.",
        "duration": "HUGE",
        "ep_cost": 490,
        "using_time": "3 rounds",
        "affecting_stats": ["dex"],
        "creator": "Sigwald",
    },
    "entangle": {
        "name": "Entangle",
        "type": "Attack",
        "cost": 1297,
        "description": "Wrap whip around torso preventing arm use. Reduces opponent's fighting ability.",
        "damage": "Extremely low",
        "damage_type": "Physical",
        "ep_cost": 204,
        "using_time": "3 rounds",
        "affecting_stats": ["dex"],
        "creator": "Sigwald",
    },
    "impale": {
        "name": "Impale",
        "type": "Attack",
        "cost": 1441,
        "description": "Impale opponent tearing through armor and flesh.",
        "damage": "Above average",
        "damage_type": "Physical",
        "ep_cost": 232,
        "using_time": "3 rounds",
        "affecting_stats": ["str", "dex"],
        "creator": "Sigwald",
    },
    "sharpen_weapon": {
        "name": "Sharpen Weapon",
        "type": "Enchantment",
        "cost": 1345,
        "description": "Improve piercing weapon quality making it incredibly sharp.",
        "duration": "HUGE",
        "sp_cost": 298,
        "ep_cost": 298,
        "using_time": "3 rounds",
        "affecting_stats": ["dex"],
        "creator": "Sigwald",
    },
    "piercing_weapons_mastery": {
        "name": "Piercing Weapons Mastery",
        "type": "Combat",
        "cost": 1345,
        "description": "Best use of piercing weapons, capitalizing on advantages.",
        "creator": "Sigwald",
    },
    "spearwind_thrust": {
        "name": "Spearwind Thrust",
        "type": "Area",
        "cost": 1249,
        "description": "Rapid pinpoint piercing strikes to multiple foes.",
        "damage": "High",
        "damage_type": "Physical",
        "ep_cost": 362,
        "using_time": "4 rounds",
        "affecting_stats": ["dex"],
        "creator": "Cash",
    },
    "spot_weak_point": {
        "name": "Spot Weak Point",
        "type": "Mastery",
        "cost": 1878,
        "description": "Master anatomy to spot weak points on any species.",
        "creator": "Sigwald",
    },
    "wrist_flick": {
        "name": "Wrist Flick",
        "type": "Mastery",
        "cost": 2286,
        "description": "Turn weapon once impaled to inflict bleeding wounds and hit arteries.",
        "creator": "Sigwald",
    },
    "crippling_blow": {
        "name": "Crippling Blow",
        "type": "Combat",
        "cost": 2405,
        "description": "Powerful blows enhancing critical hit power.",
        "creator": "Sigwald",
    },
    "strike_weakness": {
        "name": "Strike Weakness",
        "type": "Combat",
        "cost": 2213,
        "description": "Strike with terrible precision, scoring more critical hits.",
        "creator": "Sigwald",
    },
    "weapon_maneuvers": {
        "name": "Weapon Maneuvers",
        "type": "Mastery",
        "cost": 3740,
        "description": "Best techniques in weapon handling. Efficient with all weapons.",
        "creator": "Sigwald",
    },
    "stun_resistance": {
        "name": "Stun Resistance",
        "type": "Combat",
        "cost": 2501,
        "description": "Reduce effects of stuns and shake off grogginess faster.",
        "creator": "Sigwald",
    },
    "charge": {
        "name": "Charge",
        "type": "Attack",
        "cost": 3656,
        "description": "Start fight by charging opponent. Can incapacitate.",
        "damage": "Extremely high",
        "damage_type": "Physical",
        "ep_cost": 276,
        "using_time": "2 rounds",
        "affecting_stats": ["str"],
        "creator": "Sigwald",
    },
    "champion_lore": {
        "name": "Champion Lore",
        "type": "Mastery",
        "cost": 2570,
        "description": "Champion lore is filled with secret techniques that affects how well a champion will be able to execute the skills of the guild.",
        "creator": "Sigwald",
        "training_caps": {2: 20, 3: 40, 4: 60, 5: 80, 6: 100},
    },
    "champion_trance": {
        "name": "Champion Trance",
        "type": "Protection",
        "cost": 2640,
        "description": "By entering a special trance, the Champion can focus his will power to create a special state of mind that will allow him to partly ignore magical attacks. This skill is known to be very difficult to control and therefore can have very varying effects.",
        "protection_category": "General",
        "duration": "High",
        "stacks": 1,
        "sp_cost": 98,
        "ep_cost": 396,
        "using_time": "6 rounds",
        "affecting_skills": ["champion_lore"],
        "affecting_stats": ["sta", "wis"],
        "creator": "Sigwald",
    },
    "crippling_blow": {
        "name": "Crippling Blow",
        "type": "Combat",
        "cost": 2405,
        "description": "Champions learn secret techniques to deliver powerful blows that greatly enhance the power of critical hits.",
        "creator": "Sigwald",
        "training_caps": {2: 15, 3: 30, 4: 45, 5: 60, 6: 80, 7: 100},
    },
    "strike_weakness": {
        "name": "Strike Weakness",
        "type": "Combat",
        "cost": 2213,
        "description": "Trained champions learn to strike their opponents with terrible precision, thus allowing themselves to score more numerous critical hits.",
        "creator": "Sigwald",
        "training_caps": {3: 15, 4: 30, 5: 45, 6: 60, 7: 80, 8: 100},
    },
    "weapon_maneuvers": {
        "name": "Weapon Maneuvers",
        "type": "Mastery",
        "cost": 3740,
        "description": "Champions of the crown are elite warriors that are taught the best techniques in weapon handling. Trained to use any kind of weapon, from dagger to halberd, they are extremly efficient in all kind of attack skill that uses a weapon, and can deliver much more damage than other warriors, even expert ones.",
        "creator": "Sigwald",
        "training_caps": {4: 15, 5: 30, 6: 45, 7: 60, 8: 80, 9: 100},
    },
    "stun_resistance": {
        "name": "Stun Resistance",
        "type": "Combat",
        "cost": 2501,
        "description": "Champions usually have mastered their willpower and are now and then able to avoid stunning hits. Anyhow, no one can really rely only on his willpower to avoid being stunned and therefore champions train intensely to reduce the effects of stuns and to shake off the groggyness faster. With great training, champions are able to reduce dramatically the length of stuns inflicted to them.",
        "creator": "Sigwald",
        "training_caps": {5: 20, 6: 40, 7: 60, 8: 80, 9: 100},
    },
    "charge": {
        "name": "Charge",
        "type": "Attack",
        "cost": 3656,
        "description": "This skill allow the Champion to start a fight by charging his opponent. Using his momentum, he can deliver a terrible blow at his opponent, which can sometimes incapacitate his opponent for a while. Trained champions have been known to cut their opponent to ribbons before they could react after a successful charge.",
        "damage": "Extremely high",
        "damage_type": "Physical",
        "ep_cost": 276,
        "using_time": "2 rounds",
        "affecting_skills": ["champion_lore"],
        "affecting_stats": ["str"],
        "creator": "Sigwald",
        "training_caps": {6: 20, 7: 40, 8: 60, 9: 80, 10: 100},
    },
}


def get_guild_tree(guild_id):
    """Get complete guild tree data."""
    return GUILDS.get(guild_id)


def get_skill_data(skill_id):
    """Get skill detail data."""
    return SKILL_DATABASE.get(skill_id)


def get_guild_skills(guild_id):
    """Get all skills for a guild with level requirements."""
    guild = GUILDS.get(guild_id)
    if not guild:
        return {}

    skills = {}
    for level, skill_list in guild["skills"].items():
        for skill_id, skill_type, cost in skill_list:
            skill_data = get_skill_data(skill_id)
            if skill_data:
                skills[skill_id] = {
                    "level": level,
                    "type": skill_type,
                    "cost": cost,
                    **skill_data,
                }

    return skills


def get_full_guild_tree(guild_id, depth=0):
    """Get full guild tree with all children recursively."""
    guild = GUILDS.get(guild_id)
    if not guild:
        return None

    result = {
        "id": guild_id,
        "name": guild["name"],
        "level": guild["level"],
        "depth": depth,
        "skills": get_guild_skills(guild_id),
        "children": [],
    }

    for child_id in guild.get("children", []):
        child_tree = get_full_guild_tree(child_id, depth + 1)
        if child_tree:
            result["children"].append(child_tree)

    return result


def list_all_guilds():
    """List all guild IDs."""
    return list(GUILDS.keys())


def get_guild_prerequisites(guild_id):
    """Get prerequisites for joining a guild."""
    guild = GUILDS.get(guild_id)
    if not guild:
        return []

    prereqs = guild.get("prerequisites", [])
    parent = guild.get("parent")
    if parent and parent not in prereqs:
        prereqs.append(parent)

    return prereqs
