"""
Extract ASCII maps from HTML files and create Map Builder compatible format
"""

import os
import re

# Create output directory
os.makedirs("/root/.openclaw/workspace/reddragon/world/maps", exist_ok=True)

# Map files to process
map_files = {
    "blackavar": "/root/.openclaw/workspace/iom_maps/blackavar.html",
    "gossamer": "/root/.openclaw/workspace/iom_maps/gossamer.html",
    "sombre": "/root/.openclaw/workspace/iom_maps/sombre.html",
    "darkcaverns": "/root/.openclaw/workspace/iom_maps/darkcaverns.html",
    "hyboria": "/root/.openclaw/workspace/iom_maps/hyboria.html",
    "southcape": "/root/.openclaw/workspace/iom_maps/southcape.html",
    "emerald": "/root/.openclaw/workspace/iom_maps/emerald.html",
    "mists": "/root/.openclaw/workspace/iom_maps/mists.html",
    "twin_islands": "/root/.openclaw/workspace/iom_maps/twin_islands.html",
    "everrest": "/root/.openclaw/workspace/iom_maps/everrest.html",
    "oddworld": "/root/.openclaw/workspace/iom_maps/oddworld.html",
}

# The blackavar map was already fetched via web_fetch
# Let me save it first
blackavar_content = """WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbbbbbbbbbbbbbbbbbbbWWWWWWWWWWWWWWWWWWWWWWbbbbbbWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbbbbbbbbbbbbffffddddddddddddddddddWWWWWWWWWWWWWWWWbbfffffbbWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWbbbbbbbbbbbbbffffffffffffffffhhhddddddddddddddddddWWWWWWWWWWWWWsffffffffbbbbbbWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWbbbbbffffffffffffffffffffffffffhhhMhhhhhhdddddddddddddddsWWWWWWWWWWssfffffffffffffbbbbbbbbbbbbbWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWbbbbbfffffFFFFFFFFfffffffffffffffffhMMMhhhhhhddddddddddddddddsWWWWWWWWssssffffffffffffffffffffffffbbbbbbbbbbbWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWbbfffffffffFFFFFFFFFfffffffffffffffhMMMhhhhhhhhdddddddddddddddsssWWWWssssssfffffffffffffffffffffffffffffffffbbbbbbbbMWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWbffffffffffFFFFFFFFFFFffffffffffffffhhMMhhhhhhhhhhdddddddddddddsssssWWWsssssssfffffffffffffffffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWbffffffffffFFFFFFFFFFFFFffffffffffffhhhMMhhhhhhhhhhhdddddddddddddssssRRRssssssffffffffffffffffffffffffMfffffffffffffbWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWbffffffffFFFFFFFFFFFFFFFFFffffffffffhhhhMMMMhhhhhhhhhdddddddddddddddssRRRsssssffffffffffffffffffffffffMMMfffffffffffbWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWbffffffffFFFFFFFFFFFFFFFFFFfffffffffhhhMMMMMMvMMMMMhhdddddddddddddddddssRRssssfffffffffffffffffffffffMMMMfffffffffffffbWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWbfffffffFFFFFFFFFFFFFFFFFFFFffffffffhhMMMMMMMvMMMMhhhdddddddddddddddddddssRRsfffffffffffffffffffffffMMMMMMLLfffffffffffbWWWWWWWWWWWWWWWWWWWWW
WWWWWWbffffffffFFFFFFFFFFFFFFFFFFFFffffffffhMMMMMMMvMMMMMMhhddddddddddddddddddddsRRffffffffffffffffffffffffMMMMMLLLLLffffffffffbWWWWWWWWWWWWWWWWWWWWW
WWWWWbfffffffffffFFFFFFFFFFFFFFFFFFFLLfffffhhMMMMMMVMMMMMhhddddddddddddddddddddddsRRffffffffffffffffffffffMMMMMffLLLLLffffffffbWWWWWWWWWWWWWWWWWWWWWW
WWWWWbfffffffffffffFFFFFFFFFFFFFFFFFLLLfffffhhMMMMMMMMMMhhhdddddddddddddddddddddddmRRfffffffffffffffffffffffMMMMMMfLLLLffffffbWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWbfffffffffffffFFFFFFFFFFFFFFFFFLLfffffffhhMMMMMMMMhhhddddddddddddddddddddddddfmRRffffffffffffffffffffffffMMMMMLLfffffffbWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWbbbbffffffffffffFFFFFFFFFFFFFFFFFFFFFfffffffhhMMMMMMhhhddddddddddddddddddddddddffmmRRffffffffffffffffffffffffffMMMMffffffffbWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWbbbffffffffffffFFFFFFFFFFFFFFfffffffhhhhMMMMhhdddddddddddddddddddddddddfffmmmRRfffffffffffffffffffffffffffMMMMfffffffbWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWbbbbfffffffffffFFFFFFFFFFFFfffffffhhhMhhdddddddddddddddddddddddddfffmmmRRRRfffffffffffffffffffffffffffMMMffffffffbWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWbffffffffffffFFFFFFFFFFFffffffffhMhdddddddddddddddddddddddppffffmRRR##RRfffffffffffffffffffffffffffMffffffffbWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWbfffffffffffffFFFFFFFFFffffffffMhddddddddddddddddddddpppppffffRRRf####RRffffffffffffffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWbffffffffffffffFFFFFFffffffffMMdddddddddddddddpppppppppfffffRRffff+fffRRffffffffffffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWbfffffffffffffffFFFffffffffMMMdddddddddpppppppppppffffffffRRfffffffffRRffffffffffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWbfffffffffffffffFFfffffffMMMdddddddppppppppppppfffffffffRRfffffffffffRRfffffffffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWbffffffffffffffFfffRRRRMMMMddddpppppppppppppffffffffffRRfffffffffffffLLLfffffffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWbffffffffffffFFRRRRfMMMMMBBBBBBBBppppppppfffffffffffRRRfffffffffffffffLLLLLLLfffffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWbffffffffFFFRRfffMMMMMBBBBBBBBBBBppppffffffffffffRRFRRfffffffffffffffLLLLLLLLffffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWbffffffFRRRRRfffMMMMMBBBBBBBBBBfffppffffffffffffRRFFFRRfffffffffffffffLLLLLLLLLfffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWRfffffRRRFFffffffMMMBBBBBBBBBffffffffffffffffffRRFFFFFRRfffffffffffffffLLLLLLLLfffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWRRRRIRfFFffffffffMBBBBBBBBfffffffffffffffffffRRFFFFFFFRffffffffffffffffffLLLLLfffffffffffffffffffffffbWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWRfffMRRFffffffMMBBBBBBffffffffffffffffffRRRRRFFFFFFFFRfffffffffffff+--+ffLLf/ffppppppppffffffffffffbWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWbfffMMMRRfffMMMMMBBBBBBffffffffffffffRRRRRFFFFFFFFFFFFRffffffffffffffffffffff/ffffppppppppffffffffffffbWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWbfffMMMFRfMMMMMMMMBBBBfffffffffffRRRRRFFFFFFFFFFFFFFFFRffffffffffffffffffffffff+-+ffffffpppppppppfffffffffffbWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWbfffMMMMMMRMMMMMMMMMMMBBBBfffffffffffRRFFFFFFFFFFFFFFFFFFFFRffffffffffffffffffffffffffffppppppppppffffffffffbWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWccMMMMMfFMMMMMMMMMMMMBBBBfffffffffffRRFFFFFFFFFFFFFFFFFFFFFRffffffffffffffffffffffffffffffppppppppppfffffffffbWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWcccccMMMMMffFFMMMMMMMMMBBBBfffffffffRRRRFFFFFFFFFFFFFFFFFFFFFFRffffffffffffffffffffffffffffffffppppppppppffffffffbWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWcMMMMMMffffffFf#ffMMMMMMMBBfffffffffRRFFFFFFFFFFFFFFFFFFFFFFFFRFfffffffffffffffffffffffffffffffffffppppppffffffffffcWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWcMddMMfffffffFFfffMMMMMMMMBffffffffffRRFFFFFFFFFFFFFFFFFFFFFFFFFFfffffffffffffffffffffffffffffffffffffffppppffffffffffcWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWcMdddMMMffFFFFffffffMMMMMMMMMfffffffffffRRFFFFFFFFFFFFFFFFFFFFFFFFfffffffffffffffffffffffffffffffffffffffffffffffffffffcWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWcMMMMfffFFFFffffffMMMMMMMMMMfffffffffRRFFFFFFFFFFFFFFFFFFFFFFFffffffffffffffffffffffffffffffffffffffffffffffffffffffffcWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWccMffFFFFFffffffMMMMMMMMMfffffffffRRRFFFFFFFFFFFFFFFFFFfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWbffffffffFFFFFFffffffMMMfffffffffMMffffffffRRffRFFFFFFFFFFFFFFffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWbffffFFFFFFffffffffffMMMMfffffffffMMfffffffffRRfffRFFFFFFFFFFfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWbbffffffFFFFffffffffffffffMMMfffffffffMMfffffffffRRfffffRFFFFFFffffffffffffffffffffffffffffffffffffffffffffffffffffffffLfffffffffffffffcWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWbbffffffffFFFfffffffffffffffffMMMfffffffffMMfffRRfffffffRFFFfffffffffffffffffffffffffffffffffffffffffffffffffffffffffLLLfffffffffffffffcWWWWWWWWWWWWWWWWW
WWWWWWWWWWWbbfffffffffffFfffffffffffffffMMMMMffffffffMMMfRRfffffffMMMFffffffffffffffffffffffffffffffffffffffffffffffffffffffLfffffffffffffffcWWWWWWWWWWWWWWWW
WWWWWWWWWWWbffffffffffffffffffffffffffffffMMMMMffffffMMMMMRffffffffMMMMffffffffffffffffffffffffffffffffffffffffffffffffLfffffffffffffffffffffffcWWWWWWWWWWWWWWW
WWWWWWWWWWWbbffffffffffffffffffff/fffffffffMMMMfffffffMMMfffffffffffffffffffffffffffffLLfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcWWWWWWWWWWWWWWW
WWWWWWWWWWWWWbbbffffffffffffff?fffffffMMMMffffffffMfffffffffffffffffffffffffffffffffLLLLffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWbbbbffffffffffffff|ffffffffMMffffffffffffffffffffffffffffffffffffffLLLLLLffffff#ffffffffffffffffffffffffffffffffffffffffffffffffffffffffcWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWbbbbbffffff|ffffffffffffMMfffffffffffffffffffffffffffffffffffffLLLLfffffff+---------------------+------------------+cWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWbbbbffffffffffffMffffffffffffffffffffffffffffffffffffffLLLLffffffffffLfffffffffffffffffffffffffffffffffffffffffffffffffffffffcWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWccccfffffffMfffffffffffffffffffffffffffffffffffffffLLffffffffffffffLLffffffffffffffffffffffFFfffffffffffffffffffffffffffffffcWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWccccfffMMfffffffffffffffffffffffffffffffffLffffffffffffffffffLLffffffffffffffffffffffFFFFfffffffffffffffffffffffffffffffcWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWccccccfffffffffffffffffffffffffffffffLLLLfffffffffffffffffffffffffffffffffffffffFFFFFFfffffffffffffffffffffffffffffffcWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWccccffffffffffffffffffffffffffffffLLLLLffffffffffffffffffMMffffffffffffffffFFFFFffffffffffffffffffffffffffffff|HHcWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbbbfffffffffffffffffffffffffLLLffffffffffffffffffffMMMMMffffffFFfffffffffffffffffffffffH|HHHcWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbbbbbbbbfffffffffffffffLfffffffffffffffffffffMMMMMMffffFFFFFffFfffffffffffffffHH|HHcWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbbbbbffffffffffffffffffffffffffffffMMMMMMMMFFFFFFFFFFFffffffffffffffHHHH|HHcWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbfffffffffffffffffffffffffffMMMMMMMMMMFFFFFFFFFFFFFffffffHHHHHHHH|HcWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbfffffffffffffffffffffffMMMMMMMFFFFFFFFFFFFFFFFFHHHHHHHHHHHH|HHcWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbfffffffffffffffffffffLLLffffffffFFMMMMMFFFFFFFFFFFFHHHHHHHHHHHHHHHHHHHH|HcWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW####fffffffffffffffLLfffffffFFFFFMMMMMFFFFFFFHHHHHHHHHHHHHHHHHHHHH|cWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW###+ffffffffffffffffFFFFFFFMMMMFFFFFFFFFFFFHHHHHHHHHHHHHHHHHHH|ccWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#ffffffffffffffffFFFFFFFFFFhMFFFFFFFFFFFFFFFFFFFHHHHHHHHHHH###cWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbf+--------------------------------------------------###cWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbffffffffffFFFFFFFFFFhMFFFFLLFFFFFFFFFFFFFFFFFFHHHHHHH###cWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbffffffffFFFFFFFFFFFhMMMFFLLLLFFFFFFFFFFFFFFFFFFHHHHHHH|fcWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbfffffFFFFFFFFFFFFFhhhMMMFFFLLFFFFFFFFFFFFHHHHHHHHHHHHHHcWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbfffffFFFFFFFFFFFFFhhhhhhMMFFLFFFFFFFFHHHHHHHHHHHHHHHHHHHHHcWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbffffffFFFFFFFFFFFFFhhhhhhMMMFFFFFFFFHHHHHHHHHHHHHHHHHHHHHHHcWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWccfffffffffFFFFFFFFFFhhhhhMMFFFFFFFFFHHHHHHHHHHHHHHHHHHHHHHcWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWcccccccffffffffFFFFFFFhhMFFFFFFFFFFFFHHHHHHHHHHHHHHHHHHHHHcWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWcccccccfffffffffhhfffFFFFFFHHHHHHHHHHHHHHHHHHHHHHHHH+cWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbbbbbbbfffffffffHHHHHHHHHHHHHHHHHHHHHHHHHHHH|HcWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbbbbbbbbbbbbbHHHHHHHHHHHHHHHHHccccHHHHcWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbbbbbbbbbbbbbbbbbbbcccc###cWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWbbbb###bbWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"""

with open("/root/.openclaw/workspace/iom_maps/blackavar.html", "w") as f:
    f.write(blackavar_content)

# Process each map
for map_name, filepath in map_files.items():
    if not os.path.exists(filepath):
        print(f"Missing: {filepath}")
        continue
    
    with open(filepath, "r") as f:
        content = f.read()
    
    # Extract ASCII map - remove HTML tags and links
    # The maps are pure ASCII with [?](url) markers
    lines = content.split('\n')
    ascii_lines = []
    for line in lines:
        # Skip empty lines
        if not line.strip():
            continue
        # Remove HTML tags if any
        clean = re.sub(r'<[^>]+>', '', line)
        # Remove markdown link syntax [text](url)
        clean = re.sub(r'\[.*?\]\(.*?\)', '', clean)
        # Remove any remaining [?] or [O] markers
        clean = re.sub(r'\[[^\]]*\]', '', clean)
        if clean.strip():
            ascii_lines.append(clean)
    
    # Save clean ASCII map
    output_path = f"/root/.openclaw/workspace/reddragon/world/maps/{map_name}_map.txt"
    with open(output_path, "w") as f:
        f.write('\n'.join(ascii_lines))
    
    print(f"Saved {map_name}: {len(ascii_lines)} lines")

print("\nAll maps extracted!")
